### ISSUE TITLE
Document customization points and ideas

### ISSUE THREAD

**Issue by qchateau** [qchateau/packio#6]
- Mutex-free dispatcher
- Client template
- Session counting
- ?

**Comment by stracedude** [comment]
Hello! Good project!
I think it would be good to implement the following ideas:

- standealone asio
- rpc over other formats: json, protobuf
- context of the task, as in rpclib (this_server_t): disable task, stop server and so on.

**Comment by qchateau** [comment]
Hi, thanks for the feedback.

- Standalone asio is definitely something I can look into.
- RPC over other formats: JSON-RPC could probably be useful, although as I don't have any use for it and packio was not designed to be protocol-independent, I'll probably not find the courage to do it.
- I don't understand what you mean by context of the task, and what you want to achieve with it. If you want to interfere with the server from within the task, you can just capture whatever you need in the lambda you are binding as procedure.

**Comment by qchateau** [comment]
Closing this as packio is now protocol independent and supports standalone asio
