### ISSUE TITLE
packio in cmake project

### ISSUE THREAD

**Issue by yevsev** [qchateau/packio#68]
I am trying to use packio in my cmake project but I get a few compiler errors:

error 1
```
.conan/data/packio/2.2.0/_/_/package/0c0791061c9ce0b41dcaec85e4a8aeeb1bfa1a31/include/packio/json_rpc/hash.h:66:8: error: redefinition of ‘struct std::hash<boost::json::value>’
   66 | struct hash<boost::json::value> {
...
.conan/data/boost/1.80.0/_/_/package/cb420f7a9d4f5344407adad933bfd4a05ab58ddd/include/boost/json/value.hpp:4030:8: note: previous definition of ‘struct std::hash<boost::json::value>’
 4030 | struct hash< ::boost::json::value > {
```

error 2
```
error: ‘using element_type = class packio::dispatcher<packio::nl_json_rpc::rpc, packio::default_map, std::mutex>’ {aka ‘class packio::dispatcher<packio::nl_json_rpc::rpc, packio::default_map, std::mutex>’} has no member named ‘add_coro’
  108 |     server->dispatcher()->add_coro(
```

error 3
```
error: ‘awaitable’ in namespace ‘packio::net’ does not name a template type
  109 |             "pow", io, [](int a, int b) -> packio::net::awaitable<int> {
```

It seems that boost asio is not correctly linked somehow?

My cmake code for including packio:
```
include("${CMAKE_MODULE_PATH}/conan.cmake")
conan_cmake_configure(REQUIRES packio/2.2.0
        GENERATORS cmake_find_package)
conan_cmake_autodetect(settings)
message("external: settings = ${settings}")
conan_cmake_install(PATH_OR_REFERENCE .
        BUILD missing
        REMOTE conancenter
        SETTINGS ${settings})
```

Any help would be very much appreciated.

UPDATE:
I am getting this error even when running test_package:
```
packio$ conan test test_package/ packio/2.2.0
```
```
.conan/data/packio/2.2.0/_/_/package/0c0791061c9ce0b41dcaec85e4a8aeeb1bfa1a31/include/packio/json_rpc/hash.h:66:8: error: redefinition of ‘struct std::hash<boost::json::value>’
   66 | struct hash<boost::json::value> {
...
.conan/data/boost/1.80.0/_/_/package/cb420f7a9d4f5344407adad933bfd4a05ab58ddd/include/boost/json/value.hpp:4030:8: note: previous definition of ‘struct std::hash<boost::json::value>’
 4030 | struct hash< ::boost::json::value > {
```
I have no experience with conan so please forgive me if I am missing something obvious.

**Comment by qchateau** [comment]
Error 1 is on me, probably a change in the latest version of boost. I need to fix it.

Error 2 and 3 are probably due to your compiler not supporting coroutines (or at least, asio detecting that it does not). What compiler and which version of it are you using ? With what compilation flags ?

**Comment by yevsev** [comment]
Thanks for your quick reply.

Compiler I use:
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

**Comment by qchateau** [comment]
I fixed error 1 in packio 2.3.0

Errors 2 and 3 I can't explain. GCC-11 on Ubuntu 22.04 is tested with coroutines in the CI.

**Comment by yevsev** [comment]
Thanks for your answer and thanks for sharing this amazing library with the world.

I have a question regarding conan/cmake:
My project only uses cmake and I am unable to use packio in my project in a neat way. Do you know of any method (cmake only) to include packio?
Have been trying to get this to work for 3 days.

**Comment by qchateau** [comment]
Packio is header only so you can just add it as a git submodule to your project and use `target_include_directories`. If you're using standalone asio (instead of boost) you need to define `PACKIO_STANDALONE_ASIO=1`

You can adapt the example below:
```cmake
add_executable(your_application main.cpp)
# find and link boost or asio
# ... up to you ...
target_include_directories(your_application PRIVATE ./packio/include)
target_compile_definitions(your_application PRIVATE PACKIO_STANDALONE_ASIO=1) # if you use asio
```

**Comment by yevsev** [comment]
I got it to work, thanks for your help!
