### ISSUE TITLE
Omit data field in error response

### ISSUE THREAD

**Issue by computerquip-work** [qchateau/packio#80]
Is there any way to get the response to omit the data field? For the most part, it's sort of redundant information for me. If I use `set_error()` with no arguments, it gets set to `unknown error` which is extra redundant since that's already what's in the `message` field of the response.

**Comment by computerquip-work** [comment]
I suppose another issue is that if I set `data` to anything that isn't a string, `message` gets set to "unknown error" seemingly unconditionally.

**Comment by qchateau** [comment]
Hum, while that seems like a straightforward change, is it really worth changing the current behavior ? I don't think redundant information in an error response is a big deal.
Could you give more information as to why you think this is an issue that needs fixing ?

**Comment by computerquip-work** [comment]
Sorry, I ended up going a different route. The reason I wanted this is because it was breaking *my* code. Trying to generically log errors returned by packio was pretty rough and often made no sense. I didn't want to change an already existing system just to fit packio.
